plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.5'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'com.diffplug.spotless' version '7.0.2'
    id 'com.google.cloud.tools.jib' version '3.4.5'
}

group = 'com'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

ext {
    set('springAiVersion', "1.0.0-M6")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // Swagger UI
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'

    // JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    // rest assured
    testImplementation 'io.rest-assured:rest-assured:5.5.1'

    // Spring AI
    implementation 'org.springframework.ai:spring-ai-openai-spring-boot-starter'    // OpenAI
//    implementation 'org.springframework.ai:spring-ai-anthropic-spring-boot-starter' // Anthropic

    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'com.mysql:mysql-connector-j'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:mysql'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

// compileJava task가 실행되기 전에 spotlessApply task를 실행하도록 설정: spotlessApply -> compileJava
tasks.named('compileJava') {
    dependsOn 'spotlessApply'
}

spotless {
    java {
        googleJavaFormat().aosp()   // Google Java Format 적용 AOSP(Andriod Open Source Project) 스타일: 탭은 4칸
        removeUnusedImports()       // 사용하지 않는 import문 제거
        leadingTabsToSpaces(4)      // 탭을 4칸 공백으로 변경
        importOrder()               // import문 정렬
        trimTrailingWhitespace()    // 뒤에 공백 제거
        endWithNewline()            // 파일 끝에 개행 추가
    }
}

jib {
    def dockerUsername = System.getenv('DOCKER_USERNAME') ?: ''
    def dockerPassword = System.getenv('DOCKER_PASSWORD') ?: ''
    from {
        image = 'amazoncorretto:21-alpine-jdk'
    }
    to {
        image = 'audejr123/donggle:latest'
        auth {
            username = dockerUsername
            password = dockerPassword
        }
    }
    container {
        jvmFlags = [
                '-Dspring.profiles.active=' + System.getenv('PROFILE'),
                '-Duser.timezone=Asia/Seoul',
                '-Dfile.encoding=UTF-8',
                '-XX:+UseContainerSupport'
        ]
    }
}
