services:
  mysql:
    container_name: mysql-donggle
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Seoul
      LC_ALL: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysql", "-u", "$MYSQL_USERNAME", "-p$MYSQL_PASSWORD", "-e", "SELECT 1;"]
      start_period: 20s
      start_interval: 3s
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - donggle-network

  redis:
    container_name: redis-donggle
    image: redis:alpine
    ports:
      - "6379:6379"
    environment: # Redis 계정 추가
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      start_period: 10s
      start_interval: 3s
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - donggle-network

  was:
    container_name: was-donggle
    image: ${DOCKER_USERNAME}/${DOCKER_REPO}:${IMAGE_TAG}
    ports:
      - "8080:8080"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --spider http://localhost:8080/actuator/health || exit 1" ]
      start_period: 36s
      start_interval: 5s
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ${WAS_LOG_PATH}:${LOGGING_DIR}
      - file-storage:${FILE_UPLOAD_PATH}  # 파일 업로드 볼륨 매핑
    networks:
      - donggle-network

networks:
  donggle-network:
    driver: bridge

volumes:
  mysql-data:
     external: true
  file-storage:
     external: true
