spring:
  application:
    name: donggle

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        show_sql: true
    open-in-view: false
  
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /
  error:
    include-stacktrace: never
    
jwt:
  secret: ${JWT_SECRET:abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789}
  access-token-expiration-minutes: 60  # 1시간
  refresh-token-expiration-minutes: 10080  # 7일
    
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    com.donggle: debug
    root: ${LOGGING_LEVEL}  # TRACE < DEBUG < INFO < WARN < ERROR < FATAL < OFF

  file:
    name: ${LOGGING_DIR}/${LOGGING_FILE}

  logback:
    rollingpolicy:
      max-history: 30       # default: 7
      max-file-size: 10MB   # default: 10MB
      total-size-cap: 5GB   # default: 제한 없음
      file-name-pattern: ${LOGGING_DIR}/${LOGGING_FILE_NAME_PATTERN} # 압축해서 보관 -> 디스크 절약

# Swagger UI settings
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.donggle

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:tc:mysql:8.0:///test-database
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver

  sql:
    init:
      mode: never
